export interface Country {
  name_es: string
  code: string // ISO 3166-1 alpha-2 code
  name_en: string // For data-ai-hint
}

export const ALL_COUNTRIES: Country[] = [
  { name_es: 'Afganistán', code: 'af', name_en: 'Afghanistan' },
  { name_es: 'Albania', code: 'al', name_en: 'Albania' },
  { name_es: 'Alemania', code: 'de', name_en: 'Germany' },
  { name_es: 'Andorra', code: 'ad', name_en: 'Andorra' },
  { name_es: 'Angola', code: 'ao', name_en: 'Angola' },
  { name_es: 'Antigua y Barbuda', code: 'ag', name_en: 'Antigua and Barbuda' },
  { name_es: 'Arabia Saudita', code: 'sa', name_en: 'Saudi Arabia' },
  { name_es: 'Argelia', code: 'dz', name_en: 'Algeria' },
  { name_es: 'Argentina', code: 'ar', name_en: 'Argentina' },
  { name_es: 'Armenia', code: 'am', name_en: 'Armenia' },
  { name_es: 'Australia', code: 'au', name_en: 'Australia' },
  { name_es: 'Austria', code: 'at', name_en: 'Austria' },
  { name_es: 'Azerbaiyán', code: 'az', name_en: 'Azerbaijan' },
  { name_es: 'Bahamas', code: 'bs', name_en: 'Bahamas' },
  { name_es: 'Bangladés', code: 'bd', name_en: 'Bangladesh' },
  { name_es: 'Barbados', code: 'bb', name_en: 'Barbados' },
  { name_es: 'Baréin', code: 'bh', name_en: 'Bahrain' },
  { name_es: 'Bélgica', code: 'be', name_en: 'Belgium' },
  { name_es: 'Belice', code: 'bz', name_en: 'Belize' },
  { name_es: 'Benín', code: 'bj', name_en: 'Benin' },
  { name_es: 'Bielorrusia', code: 'by', name_en: 'Belarus' },
  { name_es: 'Birmania (Myanmar)', code: 'mm', name_en: 'Myanmar' },
  { name_es: 'Bolivia', code: 'bo', name_en: 'Bolivia' },
  {
    name_es: 'Bosnia y Herzegovina',
    code: 'ba',
    name_en: 'Bosnia and Herzegovina',
  },
  { name_es: 'Botsuana', code: 'bw', name_en: 'Botswana' },
  { name_es: 'Brasil', code: 'br', name_en: 'Brazil' },
  { name_es: 'Brunéi', code: 'bn', name_en: 'Brunei' },
  { name_es: 'Bulgaria', code: 'bg', name_en: 'Bulgaria' },
  { name_es: 'Burkina Faso', code: 'bf', name_en: 'Burkina Faso' },
  { name_es: 'Burundi', code: 'bi', name_en: 'Burundi' },
  { name_es: 'Bután', code: 'bt', name_en: 'Bhutan' },
  { name_es: 'Cabo Verde', code: 'cv', name_en: 'Cabo Verde' },
  { name_es: 'Camboya', code: 'kh', name_en: 'Cambodia' },
  { name_es: 'Camerún', code: 'cm', name_en: 'Cameroon' },
  { name_es: 'Canadá', code: 'ca', name_en: 'Canada' },
  { name_es: 'Catar', code: 'qa', name_en: 'Qatar' },
  { name_es: 'Chad', code: 'td', name_en: 'Chad' },
  { name_es: 'Chile', code: 'cl', name_en: 'Chile' },
  { name_es: 'China', code: 'cn', name_en: 'China' },
  { name_es: 'Chipre', code: 'cy', name_en: 'Cyprus' },
  { name_es: 'Colombia', code: 'co', name_en: 'Colombia' },
  { name_es: 'Comoras', code: 'km', name_en: 'Comoros' },
  { name_es: 'Corea del Norte', code: 'kp', name_en: 'North Korea' },
  { name_es: 'Corea del Sur', code: 'kr', name_en: 'South Korea' },
  { name_es: 'Costa de Marfil', code: 'ci', name_en: 'Ivory Coast' },
  { name_es: 'Costa Rica', code: 'cr', name_en: 'Costa Rica' },
  { name_es: 'Croacia', code: 'hr', name_en: 'Croatia' },
  { name_es: 'Cuba', code: 'cu', name_en: 'Cuba' },
  { name_es: 'Dinamarca', code: 'dk', name_en: 'Denmark' },
  { name_es: 'Dominica', code: 'dm', name_en: 'Dominica' },
  { name_es: 'Ecuador', code: 'ec', name_en: 'Ecuador' },
  { name_es: 'Egipto', code: 'eg', name_en: 'Egypt' },
  { name_es: 'El Salvador', code: 'sv', name_en: 'El Salvador' },
  {
    name_es: 'Emiratos Árabes Unidos',
    code: 'ae',
    name_en: 'United Arab Emirates',
  },
  { name_es: 'Eritrea', code: 'er', name_en: 'Eritrea' },
  { name_es: 'Eslovaquia', code: 'sk', name_en: 'Slovakia' },
  { name_es: 'Eslovenia', code: 'si', name_en: 'Slovenia' },
  { name_es: 'España', code: 'es', name_en: 'Spain' },
  { name_es: 'Estados Unidos', code: 'us', name_en: 'United States' },
  { name_es: 'Estonia', code: 'ee', name_en: 'Estonia' },
  { name_es: 'Esuatini (Suazilandia)', code: 'sz', name_en: 'Eswatini' },
  { name_es: 'Etiopía', code: 'et', name_en: 'Ethiopia' },
  { name_es: 'Filipinas', code: 'ph', name_en: 'Philippines' },
  { name_es: 'Finlandia', code: 'fi', name_en: 'Finland' },
  { name_es: 'Fiyi', code: 'fj', name_en: 'Fiji' },
  { name_es: 'Francia', code: 'fr', name_en: 'France' },
  { name_es: 'Gabón', code: 'ga', name_en: 'Gabon' },
  { name_es: 'Gambia', code: 'gm', name_en: 'Gambia' },
  { name_es: 'Georgia', code: 'ge', name_en: 'Georgia' },
  { name_es: 'Ghana', code: 'gh', name_en: 'Ghana' },
  { name_es: 'Granada', code: 'gd', name_en: 'Grenada' },
  { name_es: 'Grecia', code: 'gr', name_en: 'Greece' },
  { name_es: 'Guatemala', code: 'gt', name_en: 'Guatemala' },
  { name_es: 'Guinea', code: 'gn', name_en: 'Guinea' },
  { name_es: 'Guinea Ecuatorial', code: 'gq', name_en: 'Equatorial Guinea' },
  { name_es: 'Guinea-Bisáu', code: 'gw', name_en: 'Guinea-Bissau' },
  { name_es: 'Guyana', code: 'gy', name_en: 'Guyana' },
  { name_es: 'Haití', code: 'ht', name_en: 'Haiti' },
  { name_es: 'Honduras', code: 'hn', name_en: 'Honduras' },
  { name_es: 'Hungría', code: 'hu', name_en: 'Hungary' },
  { name_es: 'India', code: 'in', name_en: 'India' },
  { name_es: 'Indonesia', code: 'id', name_en: 'Indonesia' },
  { name_es: 'Irak', code: 'iq', name_en: 'Iraq' },
  { name_es: 'Irán', code: 'ir', name_en: 'Iran' },
  { name_es: 'Irlanda', code: 'ie', name_en: 'Ireland' },
  { name_es: 'Islandia', code: 'is', name_en: 'Iceland' },
  { name_es: 'Islas Marshall', code: 'mh', name_en: 'Marshall Islands' },
  { name_es: 'Islas Salomón', code: 'sb', name_en: 'Solomon Islands' },
  { name_es: 'Israel', code: 'il', name_en: 'Israel' },
  { name_es: 'Italia', code: 'it', name_en: 'Italy' },
  { name_es: 'Jamaica', code: 'jm', name_en: 'Jamaica' },
  { name_es: 'Japón', code: 'jp', name_en: 'Japan' },
  { name_es: 'Jordania', code: 'jo', name_en: 'Jordan' },
  { name_es: 'Kazajistán', code: 'kz', name_en: 'Kazakhstan' },
  { name_es: 'Kenia', code: 'ke', name_en: 'Kenya' },
  { name_es: 'Kirguistán', code: 'kg', name_en: 'Kyrgyzstan' },
  { name_es: 'Kiribati', code: 'ki', name_en: 'Kiribati' },
  { name_es: 'Kuwait', code: 'kw', name_en: 'Kuwait' },
  { name_es: 'Laos', code: 'la', name_en: 'Laos' },
  { name_es: 'Lesoto', code: 'ls', name_en: 'Lesotho' },
  { name_es: 'Letonia', code: 'lv', name_en: 'Latvia' },
  { name_es: 'Líbano', code: 'lb', name_en: 'Lebanon' },
  { name_es: 'Liberia', code: 'lr', name_en: 'Liberia' },
  { name_es: 'Libia', code: 'ly', name_en: 'Libya' },
  { name_es: 'Liechtenstein', code: 'li', name_en: 'Liechtenstein' },
  { name_es: 'Lituania', code: 'lt', name_en: 'Lithuania' },
  { name_es: 'Luxemburgo', code: 'lu', name_en: 'Luxembourg' },
  { name_es: 'Macedonia del Norte', code: 'mk', name_en: 'North Macedonia' },
  { name_es: 'Madagascar', code: 'mg', name_en: 'Madagascar' },
  { name_es: 'Malasia', code: 'my', name_en: 'Malaysia' },
  { name_es: 'Malaui', code: 'mw', name_en: 'Malawi' },
  { name_es: 'Maldivas', code: 'mv', name_en: 'Maldives' },
  { name_es: 'Malí', code: 'ml', name_en: 'Mali' },
  { name_es: 'Malta', code: 'mt', name_en: 'Malta' },
  { name_es: 'Marruecos', code: 'ma', name_en: 'Morocco' },
  { name_es: 'Mauricio', code: 'mu', name_en: 'Mauritius' },
  { name_es: 'Mauritania', code: 'mr', name_en: 'Mauritania' },
  { name_es: 'México', code: 'mx', name_en: 'Mexico' },
  { name_es: 'Micronesia', code: 'fm', name_en: 'Micronesia' },
  { name_es: 'Moldavia', code: 'md', name_en: 'Moldova' },
  { name_es: 'Mónaco', code: 'mc', name_en: 'Monaco' },
  { name_es: 'Mongolia', code: 'mn', name_en: 'Mongolia' },
  { name_es: 'Montenegro', code: 'me', name_en: 'Montenegro' },
  { name_es: 'Mozambique', code: 'mz', name_en: 'Mozambique' },
  { name_es: 'Namibia', code: 'na', name_en: 'Namibia' },
  { name_es: 'Nauru', code: 'nr', name_en: 'Nauru' },
  { name_es: 'Nepal', code: 'np', name_en: 'Nepal' },
  { name_es: 'Nicaragua', code: 'ni', name_en: 'Nicaragua' },
  { name_es: 'Níger', code: 'ne', name_en: 'Niger' },
  { name_es: 'Nigeria', code: 'ng', name_en: 'Nigeria' },
  { name_es: 'Noruega', code: 'no', name_en: 'Norway' },
  { name_es: 'Nueva Zelanda', code: 'nz', name_en: 'New Zealand' },
  { name_es: 'Omán', code: 'om', name_en: 'Oman' },
  { name_es: 'Países Bajos', code: 'nl', name_en: 'Netherlands' },
  { name_es: 'Pakistán', code: 'pk', name_en: 'Pakistan' },
  { name_es: 'Palaos', code: 'pw', name_en: 'Palau' },
  { name_es: 'Panamá', code: 'pa', name_en: 'Panama' },
  { name_es: 'Papúa Nueva Guinea', code: 'pg', name_en: 'Papua New Guinea' },
  { name_es: 'Paraguay', code: 'py', name_en: 'Paraguay' },
  { name_es: 'Perú', code: 'pe', name_en: 'Peru' },
  { name_es: 'Polonia', code: 'pl', name_en: 'Poland' },
  { name_es: 'Portugal', code: 'pt', name_en: 'Portugal' },
  { name_es: 'Reino Unido', code: 'gb', name_en: 'United Kingdom' },
  {
    name_es: 'República Centroafricana',
    code: 'cf',
    name_en: 'Central African Republic',
  },
  { name_es: 'República Checa', code: 'cz', name_en: 'Czech Republic' },
  {
    name_es: 'República del Congo',
    code: 'cg',
    name_en: 'Republic of the Congo',
  },
  {
    name_es: 'República Democrática del Congo',
    code: 'cd',
    name_en: 'Democratic Republic of the Congo',
  },
  {
    name_es: 'República Dominicana',
    code: 'do',
    name_en: 'Dominican Republic',
  },
  { name_es: 'Ruanda', code: 'rw', name_en: 'Rwanda' },
  { name_es: 'Rumania', code: 'ro', name_en: 'Romania' },
  { name_es: 'Rusia', code: 'ru', name_en: 'Russia' },
  { name_es: 'Samoa', code: 'ws', name_en: 'Samoa' },
  {
    name_es: 'San Cristóbal y Nieves',
    code: 'kn',
    name_en: 'Saint Kitts and Nevis',
  },
  { name_es: 'San Marino', code: 'sm', name_en: 'San Marino' },
  {
    name_es: 'San Vicente y las Granadinas',
    code: 'vc',
    name_en: 'Saint Vincent and the Grenadines',
  },
  { name_es: 'Santa Lucía', code: 'lc', name_en: 'Saint Lucia' },
  {
    name_es: 'Santo Tomé y Príncipe',
    code: 'st',
    name_en: 'Sao Tome and Principe',
  },
  { name_es: 'Senegal', code: 'sn', name_en: 'Senegal' },
  { name_es: 'Serbia', code: 'rs', name_en: 'Serbia' },
  { name_es: 'Seychelles', code: 'sc', name_en: 'Seychelles' },
  { name_es: 'Sierra Leona', code: 'sl', name_en: 'Sierra Leone' },
  { name_es: 'Singapur', code: 'sg', name_en: 'Singapore' },
  { name_es: 'Siria', code: 'sy', name_en: 'Syria' },
  { name_es: 'Somalia', code: 'so', name_en: 'Somalia' },
  { name_es: 'Sri Lanka', code: 'lk', name_en: 'Sri Lanka' },
  { name_es: 'Sudáfrica', code: 'za', name_en: 'South Africa' },
  { name_es: 'Sudán', code: 'sd', name_en: 'Sudan' },
  { name_es: 'Sudán del Sur', code: 'ss', name_en: 'South Sudan' },
  { name_es: 'Suecia', code: 'se', name_en: 'Sweden' },
  { name_es: 'Suiza', code: 'ch', name_en: 'Switzerland' },
  { name_es: 'Surinam', code: 'sr', name_en: 'Suriname' },
  { name_es: 'Tailandia', code: 'th', name_en: 'Thailand' },
  { name_es: 'Tanzania', code: 'tz', name_en: 'Tanzania' },
  { name_es: 'Tayikistán', code: 'tj', name_en: 'Tajikistan' },
  { name_es: 'Timor Oriental', code: 'tl', name_en: 'Timor-Leste' },
  { name_es: 'Togo', code: 'tg', name_en: 'Togo' },
  { name_es: 'Tonga', code: 'to', name_en: 'Tonga' },
  { name_es: 'Trinidad y Tobago', code: 'tt', name_en: 'Trinidad and Tobago' },
  { name_es: 'Túnez', code: 'tn', name_en: 'Tunisia' },
  { name_es: 'Turkmenistán', code: 'tm', name_en: 'Turkmenistan' },
  { name_es: 'Turquía', code: 'tr', name_en: 'Turkey' },
  { name_es: 'Tuvalu', code: 'tv', name_en: 'Tuvalu' },
  { name_es: 'Ucrania', code: 'ua', name_en: 'Ukraine' },
  { name_es: 'Uganda', code: 'ug', name_en: 'Uganda' },
  { name_es: 'Uruguay', code: 'uy', name_en: 'Uruguay' },
  { name_es: 'Uzbekistán', code: 'uz', name_en: 'Uzbekistan' },
  { name_es: 'Vanuatu', code: 'vu', name_en: 'Vanuatu' },
  { name_es: 'Venezuela', code: 've', name_en: 'Venezuela' },
  { name_es: 'Vietnam', code: 'vn', name_en: 'Vietnam' },
  { name_es: 'Yemen', code: 'ye', name_en: 'Yemen' },
  { name_es: 'Yibuti', code: 'dj', name_en: 'Djibouti' },
  { name_es: 'Zambia', code: 'zm', name_en: 'Zambia' },
  { name_es: 'Zimbabue', code: 'zw', name_en: 'Zimbabwe' },
  { name_es: 'Palestina', code: 'ps', name_en: 'Palestine' },
  { name_es: 'Ciudad del Vaticano', code: 'va', name_en: 'Vatican City' },
]
